version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dependabot"
    schedule:
      interval: "daily"
    registries:
      - cg-registry

# registries:
#   cg-registry:
#     type: "docker-registry"
#     url: "cgr.dev" # URL of the private registry
#     username: "${{secrets.CGR_PULL_ID}}"
#     password: "${{secrets.CGR_PULL_TOKEN}}"
