---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-cli
  params:
    - name: BASE_IMAGE
      description: |
        The base image for the task.
      type: string
      # TODO: Deprecate use of root image.
      default: cgr.dev/chainguard/git:2.39.0

  results:
    - name: commit
      description: The precise commit SHA after the git operation.

  steps:
    - name: git
      image: cgr.dev/chainguard/git:2.39.0