name: chainctl-auth

on:
  workflow_dispatch: {}

jobs:
  chainctl-auth:
    name: chainctl-auth
    
    runs-on: ubuntu-latest

    permissions:
      id-token: write
    
    steps:
    - name: Install chainctl and authenticate
      uses: chainguard-dev/setup-chainctl@main
      with:
        identity: ${{secrets.CHAINCTL_ID}}

    - name: Execute chainctl command
      run: |
          chainctl img repo list -o table
