name: 'Copied - Setup chainctl'

on:
  workflow_dispatch: {}

jobs:
  chainctl-auth:
    name: chainctl-install
    runs-on: ubuntu-latest
    steps:
    - name: Install chainctl
      run: |
            cd $(mktemp -d)
    
            # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
            os=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
            if [[ "${os}" == "macos" ]]; then
              os="darwin"
            fi
    
            arch="${{ runner.arch }}"
            if [[ "${arch}" == "X64" ]]; then
              arch="x86_64"
            elif [[ "${arch}" == "ARM64" ]]; then
              arch="arm64"
            fi
    
            url="https://dl.enforce.dev/chainctl/latest/chainctl_${os}_${arch}"
            out="chainctl"
            if [[ "${os}" == "windows" ]]; then
              url="${url}.exe"
              out="${out}.exe"
            fi
            echo "Downloading chainctl from ${url}"
    
            curl -o ./${out} -fsL "${url}"
            chmod +x ./${out}
            echo "$(pwd)" >> $GITHUB_PATH

    - name: Auth chainctl
      run: |
        if chainctl auth login --identity "${{secrets.CHAINCTL_ID}}" -v=2; then
          echo Logged in as ${{secrets.CHAINCTL_ID}}!
        else
          echo Unable to assume the identity ${{secrets.CHAINCTL_ID}}.
          exit 1
        fi
        if ! chainctl auth configure-docker --identity "${{secrets.CHAINCTL_ID}}"; then
          echo Unable to register credential helper as ${{secrets.CHAINCTL_ID}}.
          exit 1
        fi
          echo Failed to log in with invite code
          exit 1
        fi
