name: cosign-verify

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image name (without tag)'
        required: true
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  verify-signature:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
    - name: Install chainctl and authenticate
      uses: chainguard-dev/setup-chainctl@main
      with:
        identity: ${{secrets.CHAINCTL_ID}}

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.9.0

    - name: Verify signature
      run: cosign verify \
        --certificate-oidc-issuer=https://issuer.enforce.dev \
        --certificate-identity-regexp="https://issuer.enforce.dev/${{secrets.CATALOG_SYNCER}}|${{secrets.APKO_BUILDER}}" \
        cgr.dev/${{secrets.PARENT}}/${github.event.inputs.image}:${github.event.inputs.tag} | jq
