name: Auto Label Issues

on:
  issues:
    types:
      - opened

jobs:
  add-support-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Add Label to Issue
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;
            const supportUsers = ["sschubertchainguard","someoneelse"];
            const labelToAdd = "customer-support";

            if (supportUsers.includes(creator)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: [labelToAdd],
              });
            }
